### ISSUE TITLE
How to update to version 0.6.5 using conda?

### ISSUE THREAD

**Issue by SK-N-BE** [phac-nml/staramr#109]
I used conda to install staramr (current version 0.5.1). Using conda,  it seems only possible to install version 0.5.1. : https://anaconda.org/bioconda/staramr
How may I get the newest version? Do I have to install it manually or by using pip?

**Comment by SK-N-BE** [comment]
using `conda update staramr `resulted in updating the 0.5.1 version to 0.6.1 so that the MLST is now available.
However, why does conda not update to version 0.6.5?

**Comment by Takadonet** [comment]
We have not made a version 0.6.5 release and currently in [progress](https://github.com/phac-nml/staramr/pull/107). 

For why version 0.6.1 is not available is little strange since when I do a conda search staramr it appears.  On site [itself](https://anaconda.org/bioconda/staramr) it shows that noarch installation is at v0.6.1 but linux-64 and osx-64 is still at v0.5.1. Last update of the bioconda recipe was done by the [bioconda bot ](https://github.com/bioconda/bioconda-recipes/commits/master/recipes/staramr/meta.yaml) . We will take a look to see what it happening.

**Comment by SK-N-BE** [comment]
Thank you for your comment!
Yes, when I removed staramr and re-installed it using conda, the 0.5.1 version was installed. However, as described above, updating staramr following installation, resulted in updating version 0.5.1 to Version 0.6.1

**Comment by quocviet0908** [comment]
Hi there.
I'm trying to update staramr tu 0.6.1 from both outside and inside the staramr environment but still no luck so far.
Could you please help me with this issue?

**Comment by Takadonet** [comment]
There is an issue that we are trying to address where if you ask for **latest** version to be installed it with following command **conda install staramr**, it will install v0.5.1 . Believe the reason is that we switch to noarch build but previously did arch specific in the past. V0.5.1 was the last version where we did specific arch build but moved to noarch since then.

If you wish to install the latest verison, you have to indicate the version as seen below.
**conda install staramr==0.7.1**

**Comment by quocviet0908** [comment]
Thanks very much. I have managed to install the 0.7.1 with your guidance.

**Comment by apetkau** [comment]
Running `conda install staramr` for me right now installs `0.7.2` (latest version) so I'm going to close this issue.
