### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by vappiah** [phac-nml/staramr#124]
Hi, when running staramr with the settings _staramr search --pointfinder-organism salmonella -o starout dir/*.fasta_
I got the error below. Please advice and thanks
apps/Python/Python-3.5/lib/python3.5/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce return umr_maximum(a, axis, None, out, keepdims)

**Comment by apetkau** [comment]
Hello @jotes35. Do you happen to have the input files you were using when that warning occurred? Or, was there other messages around that warning message?

Based on some searches, it seems like this warning is generated due to empty/NA values turning up when trying to find the maximum of a list of numbers, which are unexpected (https://github.com/numpy/numpy/issues/11029). Without having more details, though, it's difficult to know what is triggering this.
