### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by peflanag** [phac-nml/staramr#127]
Hi,

This might be a stupid question but is it possible to find out the coverage of my sequencing in StarAMR when running it or will i need to use a separate coverage pipeline?

Cheers,

Peter

**Comment by apetkau** [comment]
Hello @peflanag. By coverage are you referring to the number of times a particular base pair is covered by a read (e.g., https://en.wikipedia.org/wiki/Coverage_(genetics))? If so, then no staramr cannot report that for you. Since staramr operates at the level of assembled genomes it does not have access to the coverage information. You will have to use other software that operates directly on sequence reads.

**Comment by peflanag** [comment]
Hi @apetkau that actually makes sense and was a stupid question on my part. Forgot it was an assembled genome I put through it! 

Cheers for the quick reply!
