### ISSUE TITLE
aac(6')-Iaa excluded

### ISSUE THREAD

**Issue by Andrea-SS** [phac-nml/staramr#132]
Hi,

I am wondering why the gene aac(6')-Iaa_1_NC_003197 is excluded. 

Thanks!

**Comment by apetkau** [comment]
Hello @Andrea-SS ,

If I recall correctly, it's because a number of genomic samples were being predicted to be resistant to gentamicin due to the presence of this one gene but a large portion of them were not actually resistant to gentamicin (https://github.com/phac-nml/staramr/issues/27). However, you can keep `aac(6')-Iaa_NC_003197` in your results by using `--no-exclude-genes`.

Aaron

**Comment by Andrea-SS** [comment]
Thank you!
