### ISSUE TITLE
neisseria gonorrhoeae point finder database

### ISSUE THREAD

**Issue by peflanag** [phac-nml/staramr#139]
Hi,

Is it posible to use neisseria gonorrhoeae as a database?

![Screenshot 2022-02-11 at 16 08 04](https://user-images.githubusercontent.com/32863969/153626505-5ab02347-67c2-4071-b924-2f78d238f685.png)

**Comment by apetkau** [comment]
Hello @peflanag ,

Right now only *salmonella* and *campylobacter* PointFinder databases are supported since I have to look through all the files in each PointFinder database separately and make sure I am parsing them correctly. Unfortunately right now I do not have time to work on this, but it is part of a larger issue of adding support to all organisms supported by PointFinder: https://github.com/phac-nml/staramr/issues/17

**Comment by peflanag** [comment]
Ah ok! We are looking for some tool to look at clinical/reference laboratory isolates routinely and hoped this would be something that would  work for us. 

Thanks for the quick reply

**Comment by apetkau** [comment]
No problem. Glad I could help.
