### ISSUE TITLE
Include CGE-Predicted Phenotypes for PointFinder results

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#170]
As a complement to https://github.com/phac-nml/staramr/pull/167 (which included CGE-Predicted Phenotypes for ResFinder results) it would be nice to do the same thing for the PointFinder results. For example, as shown in the **Phenotype** column here https://bitbucket.org/genomicepidemiology/pointfinder_db/src/master/salmonella/phenotypes.txt

**Comment by emarinier** [comment]
As discussed, as far as I can tell, the phenotypes.txt files only exist in newer versions of the database (June 2022 onwards).

Since we don't use this version of the database, I will close this, as instructed. If we updated our version of the database used and want to implement this later, the WIP branch is here:

- dev/cge-pointfinder-prediction

**Comment by emarinier** [comment]
https://bitbucket.org/genomicepidemiology/pointfinder_db/src/master/salmonella/resistens-overview.txt

The `resistens-overview.txt` files have a `Resistance` column that can be used for Pointfinder.

**Comment by apetkau** [comment]
Fixed in #190
